### ISSUE TITLE
USER STORY - Purpose

### ISSUE THREAD

**Issue by GlennJohansson85** [GlennJohansson85/p5-shop#2]
### USER STORY - Purpose
**As a** [first-time user]  
**I want to** [quickly understand the purpose of the website]  
**So that I can** [find the page interesting and decide to explore further]
---

### Acceptance Criteria
- [x] **Criteria 1**: The homepage should clearly display the name of the website, "i SHOP".
- [x] **Criteria 2**: The website must showcase what items are being sold. 
- [x] **Criteria 3**: The website must be easy to use
- [ ] **Additional criteria as needed**
---

### Tasks
- [x] **Task 1**:  Implement navigation links that guide the user towards discovering and interacting with posts.
- [x] **Task 2**:  Add clothing categories
- [x] **Task 3**:  Add detailed page for each product
