### ISSUE TITLE
USER STORY - Browse

### ISSUE THREAD

**Issue by GlennJohansson85** [GlennJohansson85/p5-shop#3]
### USER STORY - Browse
**As a** [first-time user]  
**I want to** [browse closthes easily]  
**So that I can** [find something to buy]

---

### Acceptance Criteria
- [x] **Criteria 1**: The landing page should show what items are being sold. 
- [x] **Criteria 2**: The product grid system should be responsive in all sizes
- [x] **Criteria 3**:  It should be easy for customers to find what they are loking for
- [ ] **Additional criteria as needed**

---

### Tasks
- [x] **Task 1**: Add search function
- [x] **Task 2**: Add Categories in Navbar and Product Page
